In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

location = "datasets/Kickstartercombo.csv"

df = pd.read_csv(location)

In [2]:
df.columns

Index(['Unnamed: 0', 'ID', 'name', 'main_category', 'category', 'country',
       'state', 'goal', 'pledged', 'currency', 'launched', 'deadline',
       'backers', 'usd pledged', 'usd_goal_real', 'usd_pledged_real'],
      dtype='object')

In [3]:
df.head()

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real
0,0,1000002330,The Songs of Adelaide & Abullah,Publishing,Poetry,GB,failed,1000.0,0.0,GBP,2015-08-11 12:12:00,2015-10-09 11:36:00,0,0.0,NaN,NaN
1,1,1000004038,Where is Hank?,Film & Video,Narrative Film,US,failed,45000.0,220.0,USD,2013-01-12 00:20:00,2013-02-26 00:20:00,3,220.0,NaN,NaN
2,2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,US,failed,5000.0,1.0,USD,2012-03-17 03:24:00,2012-04-16 04:24:00,1,1.0,NaN,NaN
3,3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,US,canceled,19500.0,1283.0,USD,2015-07-04 08:35:00,2015-08-29 01:00:00,14,1283.0,NaN,NaN
4,4,1000014025,Monarch Espresso Bar,Food,Restaurants,US,successful,50000.0,52375.0,USD,2016-02-26 13:38:00,2016-04-01 13:38:00,224,52375.0,NaN,NaN

In [10]:
df['PercentToTarget']=df['pledged']/df['goal']

In [11]:
df['PercentToTarget']

0          0.000000
1          0.004889
2          0.000200
3          0.065795
4          1.047500
5          1.205000
6          0.018120
7          0.065864
8          0.096009
9          0.000000
10         1.016000
11         0.000000
12         0.000000
13         0.265600
14         0.263333
15         0.263000
16         1.000000
17         0.356200
18         1.713400
19         0.185714
20         0.096000
21         4.009486
22         1.582700
23         0.000000
24         2.754125
25         1.123800
26         0.006000
27        47.266000
28         1.000000
29         0.055800
            ...
702381     1.386150
702382     0.000000
702383     0.465720
702384     0.882750
702385     0.087500
702386     1.087000
702387     1.024500
702388     0.003600
702389     1.115800
702390     0.100000
702391     0.000000
702392     1.246000
702393     0.000000
702394     1.762571
702395     0.171125
702396     1.823179
702397     0.196039
702398     0.242000
702399     0.270000
702400     0.000000
702401     1.100200
702402     1.075000
702403     0.014706
702404     0.023692
702405     0.000000
702406     0.000500
702407     0.103333
702408     0.001333
702409     0.013333
702410     0.262000
Name: PercentToTarget, Length: 702411, dtype: float64

In [12]:
df.head()

,Unnamed: 0,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,usd pledged,usd_goal_real,usd_pledged_real,PercentToTarget
0,0,1000002330,The Songs of Adelaide & Abullah,Publishing,Poetry,GB,failed,1000.0,0.0,GBP,2015-08-11 12:12:00,2015-10-09 11:36:00,0,0.0,NaN,NaN,0.000000
1,1,1000004038,Where is Hank?,Film & Video,Narrative Film,US,failed,45000.0,220.0,USD,2013-01-12 00:20:00,2013-02-26 00:20:00,3,220.0,NaN,NaN,0.004889
2,2,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,US,failed,5000.0,1.0,USD,2012-03-17 03:24:00,2012-04-16 04:24:00,1,1.0,NaN,NaN,0.000200
3,3,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,US,canceled,19500.0,1283.0,USD,2015-07-04 08:35:00,2015-08-29 01:00:00,14,1283.0,NaN,NaN,0.065795
4,4,1000014025,Monarch Espresso Bar,Food,Restaurants,US,successful,50000.0,52375.0,USD,2016-02-26 13:38:00,2016-04-01 13:38:00,224,52375.0,NaN,NaN,1.047500

In [15]:
df.to_csv('Project4_1.csv')